FROM ubuntu:22.10

RUN apt update

RUN apt upgrade -y

RUN apt install bind9 bind9utils bind9-doc dnsutils -y

COPY ./dns/named.conf.local /etc/bind

COPY ./dns/db.rn.br /etc/bind

COPY ./dns/db.10 /etc/bind

EXPOSE 53/udp
EXPOSE 53/tcp

CMD ["/usr/sbin/named","-g", "-c", "/etc/bind/named.conf", "-u", "bind"]
